name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Two Sum Tests
      id: two-sum-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Two Sum Tests
        setup-command: "/setup.sh"
        command: "./run_tests.sh"
        timeout: 10
        max-score: 8
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TWO-SUM-TESTS_RESULTS: "${{steps.two-sum-tests.outputs.result}}"
      with:
        runners: two-sum-tests
